### ISSUE TITLE
Update to Newer Version of AlamofireObjectMapper/Swift 4.2 Compatibility

### ISSUE THREAD

**Issue by davecom** [chrisdhaan/CDYelpFusionKit#14] opened 2018-10-03 03:41 UTC
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/chrisdhaan/CDYelpFusionKit/blob/master/CONTRIBUTING.md).

Currently, the podspec ties CDYelpFusionKit to version 5.0.0 of AlamofireObjectMapper, but this has sub-dependencies that are incompatible with the latest version of Swift (4.2) as found in Xcode 10. It would be great if we can get a version of CDYelpFusionKit tied to the latest version of AlamofireObjectMapper, or more generally a version with sub-dependencies that works with Swift 4.2

**Comment by chrisdhaan** [comment] 2018-10-26 20:46
@davecom thanks for pointing this out. I'll update this weekend.

**Comment by chrisdhaan** [comment] 2018-11-03 07:50
@davecom the update has been merged in to master. I'm doing some more cleanup on the project and will release a new version tomorrow.

**Comment by davecom** [comment] 2018-11-03 14:32
Thank you, Chris! Much appreciated.

**Comment by zhuo-ran-liu** [comment] 2018-11-09 15:16
hi Chris,

I'm trying to run the code from git on swift 4.2, and it says "No such module 'Alamofire'".  I tried with commenting the line "import Alamofire", and it seems that all the dependencies are missing for some reason.
I'm quite new to swift, is there anything that I'm doing wrong? Thanks in advance.

<img width="1280" alt="screenshot 2018-11-09 at 16 11 23" src="https://user-images.githubusercontent.com/33177743/48270466-7495a380-e43a-11e8-8273-4c1f983783f5.png">

<img width="1278" alt="screenshot 2018-11-09 at 16 19 34" src="https://user-images.githubusercontent.com/33177743/48270859-4fedfb80-e43b-11e8-8eb3-30ad6b47bfaf.png">

**Comment by davecom** [comment] 2018-11-09 15:54
Hi @SylvieLiu,
You need to install `CDYelpFusionKit` using a package manager like CocoaPods or Carthage. Please see the Installation directions in the README. If you install via a package manager, it will install all of the dependencies like Alamofire.
Hope this helps!

**Comment by zhuo-ran-liu** [comment] 2018-11-09 16:04
> Hi @SylvieLiu,
> You need to install `CDYelpFusionKit` using a package manager like CocoaPods or Carthage. Please see the Installation directions in the README. If you install via a package manager, it will install all of the dependencies like Alamofire.
> Hope this helps!

Thanks for the quick response @davecom .

I created a pod and add the line "pod 'CDYelpFusionKit', '~> 1.5'" to each target, I also tried to clean up the project and rebuild. However, it doesn't help, the modules are still missing for some reason.

I also tried to integrate it the Kit in a empty project, it builds successfully. However, the frameworks appear red, and I'm getting "nw_proxy_resolver_create_parsed_array PAC evaluation error: NSURLErrorDomain: -1003" error in my console log. Is it normal?

<img width="1280" alt="screenshot 2018-11-09 at 17 15 32" src="https://user-images.githubusercontent.com/33177743/48274406-8891d300-e443-11e8-94c1-5b57e84ac8bc.png">

<img width="1280" alt="screenshot 2018-11-09 at 17 16 12" src="https://user-images.githubusercontent.com/33177743/48274432-98a9b280-e443-11e8-8b08-fd1df2e94957.png">

**Comment by davecom** [comment] 2018-11-09 23:44
I assume you are opening the workspace file and not the regular xcproject file?

**Comment by zhuo-ran-liu** [comment] 2018-11-10 08:20
> I assume you are opening the workspace file and not the regular xcproject file?

@davecom Hi David, that's unfortunately not the cause of the problem:/

**Comment by chrisdhaan** [comment] 2018-12-14 14:44
This has been completed in version `1.5.1`. Closing issue.

**Closed as completed by chrisdhaan** 2018-12-14 14:44 UTC
Labels: enhancement
